# Generated by Django 3.2.7 on 2021-10-23 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0003_alter_course_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrolled',
            new_name='Enrollment',
        ),
    ]
