# Generated by Django 3.2.7 on 2021-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0007_auto_20211122_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wishes',
            field=models.ManyToManyField(related_name='wishes', through='Scheduler.WishList', to='Scheduler.Student'),
        ),
    ]
