# Generated by Django 3.2.7 on 2021-11-28 16:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0009_rename_course_wishlist_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='period_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
    ]
